### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by ilaipi** [apache/rocketmq-client-nodejs#8]
## What Happens?

run:
`yarn add apache-rocketmq`    
got:
```
error An unexpected error occurred: "https://registry.npm.taobao.org/apache-rocketmq: Not found".
```

 or run `npm install --save apache-rocketmq` got    
```
npm ERR! code E404
npm ERR! 404 Not Found: apache-rocketmq@latest
```

## Minimum Showcase (Required)

> Provide a minimum code or GitHub repository which can reproduce the issue.

## How to Reproduce

**Steps to reproduce the behavior:**

1. `yarn add apache-rocketmq`    or    
2. `npm install --save apache-rocketmq`   or  
3. git clone && yarn add apache-rocketmq

**Expected behavior**

1. can be installed

## Context

- **Node Version**:v8.14.0
- **SDK Version**:latest commit
- **Platform**:mac os 10.14.2 (18C54)

**Comment by XadillaX** [comment]
1.0.0-rc1 released.
